### ISSUE TITLE
Test with async code

### ISSUE THREAD

**Issue by angelocatalani** [danielefongo/setuprs#1]
Ciao @danielefongo ,
hai provato a vedere se questa macro è compatibile con i test che hanno codice asincrono?

**Comment by danielefongo** [comment]
Ciao @angelocatalani, 
questa macro ancora non supporta i test con codice asincrono. 

Appena ho un attimo vedo se riesco ad integrare l'opzione per i test asincroni.

**Comment by danielefongo** [comment]
Integrata
