### ISSUE TITLE
`when` blocks seem to lose imports from outer blocks

### ISSUE THREAD

**Issue by dallagi** [danielefongo/setuprs#2]
Consider this snippet:

```rust
#[cfg(test)]
cappuccino::tests!({
    use claim::assert_ok;

    use crate::infrastructure::some_struct::SomeStruct;

    when "when_condition" {
        it "should_work" {
            let instance = SomeStruct::new();
            assert_ok!(instance.do_something());
        }
    }
});
```

This will fail due to `SomeStruct` not being in scope.

I think it would be nice to preserve the context of the outer `when`s from the inner `it`s.

Thanks!

**Comment by danielefongo** [comment]
This is the expected behaviour.
I want to prevent usage pollution inside inner blocks; you can always use allowed `mod` items (eg: `use super::*`) inside `when` block since it is an alias for the module.

I suggest a feature-toggle to enable import propagation. 

What do you think about this?

**Comment by dallagi** [comment]
I see your point, and I'm ok with using `use super::*` as a workaround.

Personally I think the current behavior is OK and I'm not sure I'd bother adding the feature toggle.
However this is something I would document somewhere, since -at least in my experience- this is different to the usual behavior you'd expect from this kind of libraries.

**Comment by danielefongo** [comment]
I decided to follow your suggestion because it will fix a problem related to `before` propagation:

```rust
fn the_answer() -> i32 {
    42
}

before {
  let a = the_answer();
}

when using_external_utility_functions() {
  it should_pass() {
    assert_eq!(a, 42); // this won't compile
  }
}
```

Before statements are automatically injected inside the function but the method `the_answer` is not inside `when` scope.

**Comment by danielefongo** [comment]
Done ✅
